import { useMemo, useState } from 'react'
import { BadgeDollarSign, Building2, CheckCircle2, FileText, GripVertical, Package, Plus, Send, Trash2, UsersRound } from 'lucide-react'
import { Button } from '../../../components/Button'
import { Modal } from '../../../components/Modal'
import { ConfirmDialog } from '../../../components/ConfirmDialog'
import { StatusMessage } from '../../../components/StatusMessage'
import { useSalesStore, type SalesOpportunity, type SalesStatus } from '../../../lib/salesStore'
import { proposalTotal, salesStageLabels, useSalesOperationsStore, type ProposalItem, type SalesProposal } from '../../../lib/salesOperationsStore'

const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const stages:SalesStatus[]=['prospecting','qualification','diagnosis','proposal','negotiation','won','lost']
export function SalesOperationsPage(){
 const {opportunities,updateOpportunity,deleteOpportunity}=useSalesStore()
 const store=useSalesOperationsStore()
 const [tab,setTab]=useState<'pipeline'|'customers'|'products'|'proposals'>('pipeline')
 const [modal,setModal]=useState<null|'customer'|'product'|'proposal'>(null)
 const [customer,setCustomer]=useState({name:'',company:'',email:'',phone:'',segment:'',source:'Indicação'})
 const [product,setProduct]=useState({name:'',category:'Serviços',price:0,cost:0,recurring:false,active:true})
 const [proposal,setProposal]=useState({customerId:'',opportunityId:'',title:'Proposta comercial',validUntil:new Date(Date.now()+7*86400000).toISOString().slice(0,10),notes:''})
 const [items,setItems]=useState<ProposalItem[]>([])
 const [selectedLost,setSelectedLost]=useState<string[]>([])
 const [feedback,setFeedback]=useState('')
 const [confirmAction,setConfirmAction]=useState<{title:string;message:string;run:()=>void}|null>(null)
 const totalPipeline=opportunities.filter(o=>!['won','lost'].includes(o.status)).reduce((s,o)=>s+o.value,0)
 const accepted=store.proposals.filter(p=>p.status==='accepted').reduce((s,p)=>s+proposalTotal(p),0)
 const move=(item:SalesOpportunity,status:SalesStatus)=>updateOpportunity({...item,status,probability:status==='won'?100:status==='lost'?0:item.probability})
 const confirmDeleteLost=(item:SalesOpportunity)=>setConfirmAction({title:'Excluir oportunidade perdida',message:`Excluir ${item.title} da aba Perdidos? O registro e suas tarefas serão enviados para a Lixeira.`,run:()=>{deleteOpportunity(item.id);setSelectedLost(current=>current.filter(id=>id!==item.id));setFeedback('Oportunidade enviada para a Lixeira.')}})
 const toggleLost=(id:string)=>setSelectedLost(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id])
 const lostItems=opportunities.filter(item=>item.status==='lost')
 const allLostSelected=lostItems.length>0&&lostItems.every(item=>selectedLost.includes(item.id))
 const deleteSelectedLost=()=>{if(!selectedLost.length)return;setConfirmAction({title:'Excluir oportunidades perdidas',message:`Excluir ${selectedLost.length} oportunidade(s) perdidas? Os registros e suas tarefas serão enviados para a Lixeira.`,run:()=>{selectedLost.forEach(deleteOpportunity);setSelectedLost([]);setFeedback('Oportunidades enviadas para a Lixeira.')}})}
 const addItem=(productId:string)=>{const p=store.products.find(x=>x.id===productId);if(p)setItems([...items,{id:crypto.randomUUID(),productId:p.id,description:p.name,quantity:1,unitPrice:p.price,discount:0}])}
 const draftTotal=useMemo(()=>proposalTotal({items}),[items])
 const submitProposal=(e:React.FormEvent)=>{e.preventDefault();if(!proposal.customerId||!items.length)return;store.addProposal({...proposal,opportunityId:proposal.opportunityId||undefined,items,status:'draft'});setItems([]);setModal(null)}
 return <div className="page sales-ops-page">
  <StatusMessage message={feedback} tone="success" onClose={()=>setFeedback('')}/>
  <header className="page-header"><div><span className="eyebrow">RC9 • OPERAÇÃO COMERCIAL</span><h1>Espaço de Vendas</h1><p>Funil visual, clientes, catálogo e propostas em uma única operação.</p></div><Button onClick={()=>setModal(tab==='customers'?'customer':tab==='products'?'product':'proposal')}><Plus size={18}/>Novo registro</Button></header>
  <section className="sales-ops-summary"><article><BadgeDollarSign/><span>Pipeline ativo</span><strong>{money(totalPipeline)}</strong></article><article><UsersRound/><span>Clientes</span><strong>{store.customers.length}</strong></article><article><Package/><span>Serviços ativos</span><strong>{store.products.filter(p=>p.active).length}</strong></article><article><CheckCircle2/><span>Propostas aceitas</span><strong>{money(accepted)}</strong></article></section>
  <nav className="sales-ops-tabs">{([['pipeline','Funil Kanban'],['customers','Clientes'],['products','Produtos e serviços'],['proposals','Propostas']] as const).map(([key,label])=><button type="button" className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav>
  {tab==='pipeline'&&<>{lostItems.length>0&&<div className="lost-global-toolbar"><label><input type="checkbox" checked={allLostSelected} onChange={()=>setSelectedLost(allLostSelected?[]:lostItems.map(item=>item.id))}/> Selecionar todas as oportunidades perdidas</label><button type="button" disabled={!selectedLost.length} onClick={deleteSelectedLost}><Trash2 size={15}/>Excluir selecionadas ({selectedLost.length})</button></div>}<section className="sales-kanban">{stages.map(stage=><article className={`kanban-column ${stage}`} key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData('text/plain');const item=opportunities.find(o=>o.id===id);if(item)move(item,stage)}}><header><strong>{salesStageLabels[stage]}</strong><span>{opportunities.filter(o=>o.status===stage).length}</span></header><small>{money(opportunities.filter(o=>o.status===stage).reduce((s,o)=>s+o.value,0))}</small><div>{opportunities.filter(o=>o.status===stage).map(item=><article draggable onDragStart={e=>e.dataTransfer.setData('text/plain',item.id)} className="kanban-card" key={item.id}><GripVertical size={15}/>{stage==='lost'&&<input className="lost-select-checkbox" type="checkbox" checked={selectedLost.includes(item.id)} onChange={()=>toggleLost(item.id)} onClick={e=>e.stopPropagation()} aria-label={`Selecionar ${item.title}`}/>}<div><strong>{item.title}</strong><span>{item.company||item.contact}</span><b>{money(item.value)}</b><small>{item.probability}% • {item.nextStep||'Sem próxima ação'}</small></div>{stage==='lost'&&<button type="button" className="lost-delete-button" onClick={e=>{e.stopPropagation();confirmDeleteLost(item)}} title="Excluir e enviar para a Lixeira" aria-label={`Excluir ${item.title} da aba Perdidos`}><Trash2 size={15}/></button>}</article>)}</div></article>)}</section></>}
  {tab==='customers'&&<section className="sales-entity-grid">{store.customers.map(c=><article className="panel-card entity-card" key={c.id}><div className="entity-icon"><Building2/></div><div><strong>{c.company||c.name}</strong><span>{c.name}</span><small>{c.email} • {c.phone}</small><em>{c.segment} • {c.source}</em></div><button type="button" onClick={()=>store.removeCustomer(c.id)}><Trash2 size={16}/></button></article>)}</section>}
  {tab==='products'&&<section className="sales-entity-grid">{store.products.map(p=><article className="panel-card entity-card" key={p.id}><div className="entity-icon"><Package/></div><div><strong>{p.name}</strong><span>{p.category}</span><small>Venda {money(p.price)} • Margem {money(p.price-p.cost)}</small><em>{p.recurring?'Receita recorrente':'Venda única'}</em></div><button type="button" onClick={()=>store.removeProduct(p.id)}><Trash2 size={16}/></button></article>)}</section>}
  {tab==='proposals'&&<section className="proposal-list">{store.proposals.map(p=><article className="panel-card proposal-row" key={p.id}><FileText/><div><strong>{p.number} • {p.title}</strong><span>{store.customers.find(c=>c.id===p.customerId)?.company}</span><small>Válida até {new Date(p.validUntil+'T12:00:00').toLocaleDateString('pt-BR')}</small></div><b>{money(proposalTotal(p))}</b><select value={p.status} onChange={e=>store.updateProposalStatus(p.id,e.target.value as SalesProposal['status'])}><option value="draft">Rascunho</option><option value="sent">Enviada</option><option value="viewed">Visualizada</option><option value="accepted">Aceita</option><option value="rejected">Recusada</option><option value="expired">Expirada</option></select><button type="button" onClick={()=>store.removeProposal(p.id)}><Trash2 size={16}/></button></article>)}{!store.proposals.length&&<div className="empty-sales">Nenhuma proposta criada.</div>}</section>}
  <ConfirmDialog open={Boolean(confirmAction)} title={confirmAction?.title||''} message={confirmAction?.message||''} danger confirmLabel="Excluir" onClose={()=>setConfirmAction(null)} onConfirm={()=>{confirmAction?.run();setConfirmAction(null)}}/>
  <Modal open={modal==='customer'} onClose={()=>setModal(null)} title="Novo cliente"><form className="form-grid" onSubmit={e=>{e.preventDefault();store.addCustomer(customer);setModal(null)}}><label>Nome<input required value={customer.name} onChange={e=>setCustomer((current) => ({...current,name:e.target.value}))}/></label><label>Empresa<input value={customer.company} onChange={e=>setCustomer((current) => ({...current,company:e.target.value}))}/></label><label>E-mail<input type="email" value={customer.email} onChange={e=>setCustomer((current) => ({...current,email:e.target.value}))}/></label><label>Telefone<input value={customer.phone} onChange={e=>setCustomer((current) => ({...current,phone:e.target.value}))}/></label><label>Segmento<input value={customer.segment} onChange={e=>setCustomer((current) => ({...current,segment:e.target.value}))}/></label><label>Origem<input value={customer.source} onChange={e=>setCustomer((current) => ({...current,source:e.target.value}))}/></label><div className="modal-form-actions"><Button type="submit">Salvar cliente</Button></div></form></Modal>
  <Modal open={modal==='product'} onClose={()=>setModal(null)} title="Novo produto ou serviço"><form className="form-grid" onSubmit={e=>{e.preventDefault();store.addProduct(product);setModal(null)}}><label>Nome<input required value={product.name} onChange={e=>setProduct((current) => ({...current,name:e.target.value}))}/></label><label>Categoria<input value={product.category} onChange={e=>setProduct((current) => ({...current,category:e.target.value}))}/></label><label>Preço<input type="number" min="0" value={product.price} onChange={e=>setProduct((current) => ({...current,price:Number(e.target.value)}))}/></label><label>Custo<input type="number" min="0" value={product.cost} onChange={e=>setProduct((current) => ({...current,cost:Number(e.target.value)}))}/></label><label className="check-label"><input type="checkbox" checked={product.recurring} onChange={e=>setProduct((current) => ({...current,recurring:e.target.checked}))}/>Cobrança recorrente</label><div className="modal-form-actions"><Button type="submit">Salvar item</Button></div></form></Modal>
  <Modal open={modal==='proposal'} onClose={()=>setModal(null)} title="Nova proposta"><form className="proposal-form" onSubmit={submitProposal}><div className="form-grid"><label>Cliente<select required value={proposal.customerId} onChange={e=>setProposal((current) => ({...current,customerId:e.target.value}))}><option value="">Selecione</option>{store.customers.map(c=><option value={c.id} key={c.id}>{c.company||c.name}</option>)}</select></label><label>Oportunidade<select value={proposal.opportunityId} onChange={e=>setProposal((current) => ({...current,opportunityId:e.target.value}))}><option value="">Sem vínculo</option>{opportunities.map(o=><option value={o.id} key={o.id}>{o.title}</option>)}</select></label><label>Título<input value={proposal.title} onChange={e=>setProposal((current) => ({...current,title:e.target.value}))}/></label><label>Validade<input type="date" value={proposal.validUntil} onChange={e=>setProposal((current) => ({...current,validUntil:e.target.value}))}/></label></div><div className="proposal-item-add"><select defaultValue="" onChange={e=>{addItem(e.target.value);e.currentTarget.value=''}}><option value="">Adicionar produto ou serviço...</option>{store.products.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.name} — {money(p.price)}</option>)}</select></div><div className="proposal-items">{items.map((item,index)=><div key={item.id}><input value={item.description} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,description:e.target.value}:x))}/><input type="number" min="1" value={item.quantity} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,quantity:Number(e.target.value)}:x))}/><input type="number" min="0" value={item.unitPrice} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,unitPrice:Number(e.target.value)}:x))}/><input type="number" min="0" max="100" value={item.discount} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,discount:Number(e.target.value)}:x))}/><button type="button" onClick={()=>setItems(items.filter(x=>x.id!==item.id))}><Trash2 size={15}/></button></div>)}</div><div className="proposal-total"><span>Total da proposta</span><strong>{money(draftTotal)}</strong></div><div className="modal-form-actions"><Button type="submit"><Send size={17}/>Criar proposta</Button></div></form></Modal>
 </div>
}
